// src/utils/zones.js

export const zones = [
  "Aba Zone",
  "Abuja Zone 1",
  "Abuja Zone 2",
  "Accra Ghana Zone",
  "Amsterdam DSP Region",
  "Australia Zone",
  "Benin Zone 1",
  "Benin Zone 2",
  "BLW Europe Zone 1 DSP",
  "BLW SA Zone G",
  "BLW Zone C DSP",
  "Capetown Zone 1",
  "Capetown Zone 2",
  "Chad Zone",
  "Dallas Zone",
  "Durban Zone",
  "East Asia (China)",
  "Eastern Europe Region",
  "Edo North & Central Zone",
  "EWCA Zone 1",
  "EWCA Zone 2",
  "EWCA Zone 3",
  "EWCA Zone 4",
  "EWCA Zone 5",
  "EWCA Zone 6",
  "Ibadan Zone 1",
  "Ibadan Zone 2",
  "India Zone",
  "Kenya Zone",
  "Lagos Subzone A",
  "Lagos Subzone B",
  "Lagos Subzone C",
  "Lagos Virtual Zone",
  "Lagos Zone 1",
  "Lagos Zone 2",
  "Lagos Zone 3",
  "Lagos Zone 4",
  "Lagos Zone 5",
  "Lagos Zone 6",
  "Loveworld Church Zone",
  "Middle Belt Region Zone 1",
  "Middle Belt Region Zone 2",
  "Middle East and South East Asia Region",
  "Midwest Zone",
  "Ministry Center Abeokuta",
  "Ministry Center Abuja",
  "Ministry Center Calabar",
  "Ministry Center Ibadan",
  "Ministry Center Warri",
  "Nigeria South East Zone 1",
  "Nigeria South East Zone 3",
  "Nigeria South South Zone 1",
  "Nigeria South South Zone 2",
  "Nigeria South South Zone 3",
  "Northern Region 1 Zone 1",
  "Northern Region 1 Zone 2",
  "Northwest Zone 1",
  "Onitsha Zone",
  "Ottawa Zone",
  "Port Harcourt Zone 1",
  "Port Harcourt Zone 2",
  "Port Harcourt Zone 3",
  "Quebec Zone",
  "SA Zone 1",
  "SA Zone 2",
  "SA Zone 3",
  "SA Zone 5",
  "South America, New Zealand, Pacific Island Zone",
  "Southwest Zone 2",
  "Southwest Zone 3",
  "Southwest Zone 4",
  "Southwest Zone 5",
  "Toronto Zone",
  "UK Zone 1 Region 1",
  "UK Zone 1 Region 2",
  "UK Zone 2 Region 1",
  "UK Zone 3 Region 1",
  "UK Zone 3 Region 2",
  "UK Zone 4 Region 1",
  "UK Zone 4 Region 2",
  "USA Region 3",
  "USA Zone 1 Region 1",
  "USA Zone 1 Region 2",
  "USA Zone 2 Region 1",
  "Warri DSC Subzone",
  "Western Europe Zone 1",
  "Western Europe Zone 2",
  "Western Europe Zone 3",
  "Western Europe Zone 4",
  ];
  export default zones;